<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop_Down_Cara_Bayaran</name>
   <tag></tag>
   <elementGuidId>664a10dd-00fd-4933-bc7a-a131cb635185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maklumat_ArahanBayaran']//tbody//tr[7]//td[2]//span[1]//span[1]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
