<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop_Down_Jenis_Pemfaktoran</name>
   <tag></tag>
   <elementGuidId>5c91abd4-dcd9-479d-9ca0-1099a4172075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${xpath}</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[11]//td[2]//span[1]//span[1]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${xpath}</value>
   </webElementProperties>
</WebElementEntity>
