<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carian_Akaun_Belum_Bayar</name>
   <tag></tag>
   <elementGuidId>90c44636-fd0d-4ce7-9953-24069cba94d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Carian' or . = 'Carian')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='APTree']/descendant::a[@class='hlt'][contains(text(),'Carian')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carian</value>
   </webElementProperties>
</WebElementEntity>
