<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ProgramAktiviti_kod</name>
   <tag></tag>
   <elementGuidId>afd33a8f-1c1c-44ec-ae49-d0110a033a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//div[24]//td[1]//input[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[24]//td[1]//input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagrid-editable-input datagrid-filter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kod</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;panel combo-p&quot;]/div[@class=&quot;combo-panel panel-body panel-body-noheader&quot;]/div[@class=&quot;panel datagrid easyui-fluid&quot;]/div[@class=&quot;datagrid-wrap panel-body panel-body-noheader panel-body-noborder&quot;]/div[@class=&quot;datagrid-view&quot;]/div[@class=&quot;datagrid-view2&quot;]/div[@class=&quot;datagrid-header&quot;]/div[@class=&quot;datagrid-header-inner&quot;]/table[@class=&quot;datagrid-htable&quot;]/tbody[1]/tr[@class=&quot;datagrid-header-row datagrid-filter-row&quot;]/td[1]/div[@class=&quot;datagrid-filter-c&quot;]/input[@class=&quot;datagrid-editable-input datagrid-filter&quot;]</value>
   </webElementProperties>
</WebElementEntity>
