<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No_akaun_Pembekal</name>
   <tag></tag>
   <elementGuidId>43066213-eaa5-465e-90c1-1dd00ced8736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[16]/div[@title='']/div/div[@title='']//table[@class='datagrid-btable']//tr//div[contains(@class,'kodBank')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = '${class}' and (contains(text(), 'BANK ISLAM MALAYSIA BERHAD - 08013010036050') or contains(., 'BANK ISLAM MALAYSIA BERHAD - 08013010036050'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>${class}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BANK ISLAM MALAYSIA BERHAD - 08013010036050</value>
   </webElementProperties>
</WebElementEntity>
