<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu_Integrasi_Dalaman</name>
   <tag></tag>
   <elementGuidId>b9a7de35-5daf-4599-9f66-ebc85c80d111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>xpath1550719699033</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Integrasi Dalaman')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1550719699033</value>
   </webElementProperties>
</WebElementEntity>
