<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop_down_bekal_kepada_Jabatan</name>
   <tag></tag>
   <elementGuidId>d91f5133-a787-4805-9a0e-9e5547c1b6a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panelBekalKepada']/table/tbody/tr[2]/td[2]/span/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
