<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Vot_Dana_B31</name>
   <tag></tag>
   <elementGuidId>c3e4d1ec-3181-49c0-8d91-91a3aca27dd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'B31' or . = 'B31')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'B31')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>B31</value>
   </webElementProperties>
</WebElementEntity>
