<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectKod_Barang</name>
   <tag></tag>
   <elementGuidId>d7cebf26-952a-4ddf-b986-a3d663560bb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = '2110100000000000000' or . = '2110100000000000000')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'2110100000000000000')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2110100000000000000</value>
   </webElementProperties>
</WebElementEntity>
