<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop_Down_Penerima_No_Daftar</name>
   <tag></tag>
   <elementGuidId>5ab3e2a1-7695-4bab-a724-666b21a240ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[@class='edit']//td[2]//span[1]//span[1]//a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[@class='edit']//td[2]//span[1]//span[1]//a[1]</value>
   </webElementProperties>
</WebElementEntity>
