<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_kod_pembekal</name>
   <tag></tag>
   <elementGuidId>05529c66-d6d1-4b5d-985c-d50a576f8674</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>${xpath}</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@field='nama']//span[@class='textbox']//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>${xpath}</value>
   </webElementProperties>
</WebElementEntity>
