<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_proses</name>
   <tag></tag>
   <elementGuidId>9bc20110-8ce8-4bdd-a78d-c590c7eaf268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[@id='datagrid-row-r7-2-0']//input[@name='ck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[@id='datagrid-row-r7-2-0']//input[@name='ck']</value>
   </webElementProperties>
</WebElementEntity>
