<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_kod_akaun</name>
   <tag></tag>
   <elementGuidId>e313ea91-9642-4d4d-8504-32163d4a1465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'datagrid-filter-c']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kodAkaun_thead']//input[@name='kod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagrid-filter-c</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kod</value>
   </webElementProperties>
</WebElementEntity>
